package bridge

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/GrayCodeAI/yaad/internal/engine"
	"github.com/GrayCodeAI/yaad/internal/storage"
)

// AgentFiles lists supported agent memory files.
var AgentFiles = []string{"CLAUDE.md", ".cursorrules", "AGENTS.md", ".augment-guidelines"}

// Import reads agent memory files in dir and creates memory nodes.
func Import(eng *engine.Engine, dir, project string) (int, error) {
	imported := 0
	for _, fname := range AgentFiles {
		path := filepath.Join(dir, fname)
		n, err := importFile(eng, path, project)
		if err != nil {
			continue // file doesn't exist or unreadable
		}
		imported += n
	}
	return imported, nil
}

func importFile(eng *engine.Engine, path, project string) (int, error) {
	f, err := os.Open(path)
	if err != nil {
		return 0, err
	}
	defer f.Close()

	imported := 0
	scanner := bufio.NewScanner(f)
	var current strings.Builder
	nodeType := "convention"

	flush := func() {
		content := strings.TrimSpace(current.String())
		if content == "" || strings.HasPrefix(content, "#") {
			return
		}
		// Skip "Generated by Yaad" sections
		if strings.Contains(content, "Generated by Yaad") {
			return
		}
		_, err := eng.Remember(engine.RememberInput{
			Type:    nodeType,
			Content: content,
			Scope:   "project",
			Project: project,
			Agent:   "bridge:" + filepath.Base(path),
		})
		if err == nil {
			imported++
		}
		current.Reset()
	}

	for scanner.Scan() {
		line := scanner.Text()
		// Section headers hint at type
		lower := strings.ToLower(line)
		if strings.HasPrefix(line, "#") {
			flush()
			switch {
			case strings.Contains(lower, "decision") || strings.Contains(lower, "architecture"):
				nodeType = "decision"
			case strings.Contains(lower, "bug") || strings.Contains(lower, "known issue"):
				nodeType = "bug"
			case strings.Contains(lower, "task") || strings.Contains(lower, "todo"):
				nodeType = "task"
			default:
				nodeType = "convention"
			}
			continue
		}
		// Bullet points → individual nodes
		if strings.HasPrefix(line, "- ") || strings.HasPrefix(line, "* ") {
			flush()
			current.WriteString(strings.TrimPrefix(strings.TrimPrefix(line, "- "), "* "))
		} else if strings.TrimSpace(line) == "" {
			flush()
		} else {
			if current.Len() > 0 {
				current.WriteString(" ")
			}
			current.WriteString(strings.TrimSpace(line))
		}
	}
	flush()
	return imported, scanner.Err()
}

// Export writes hot-tier convention nodes back to CLAUDE.md.
func Export(store storage.Storage, dir, project string) error {
	nodes, err := store.ListNodes(storage.NodeFilter{
		Type: "convention", Project: project, Tier: 1,
	})
	if err != nil {
		return err
	}
	if len(nodes) == 0 {
		return nil
	}

	path := filepath.Join(dir, "CLAUDE.md")
	// Read existing content (preserve non-yaad sections)
	existing := readExisting(path)

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	// Write existing non-yaad content first
	if existing != "" {
		fmt.Fprintln(f, existing)
		fmt.Fprintln(f)
	}

	// Append yaad-generated section
	fmt.Fprintln(f, "<!-- Generated by Yaad — do not edit this section manually -->")
	fmt.Fprintln(f, "## Conventions")
	for _, n := range nodes {
		fmt.Fprintf(f, "- %s\n", n.Content)
	}
	return nil
}

func readExisting(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	// Strip previous yaad-generated section
	content := string(data)
	if idx := strings.Index(content, "<!-- Generated by Yaad"); idx >= 0 {
		content = strings.TrimRight(content[:idx], "\n ")
	}
	return content
}
